# Generated by Django 3.2.25 on 2024-04-04 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20240326_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email_address',
            new_name='email',
        ),
    ]
